#!/bin/bash
cd $(readlink "$(dirname "$BASH_SOURCE")" --canonicalize)

source whoshere.d/commands

parameter=$1
case $parameter in
  -v|--version)
    cat whoshere.d/version
  ;;
  -V|--verbose)
    show_verbose
  ;;
  '')
    show
  ;;
  index)
    whoshere.d/index "${@:2}"
  ;;
  -h|--help|*)
    cat whoshere.d/help
  ;;
esac
